name: cd

on:
  push:
    branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: "1.23.0"
          
          - name: Remove pontential non unix line endings 
            run: sed -i 's/\r$//' ./scripts/buildprod.sh
          
          - name: Build
            run: ./scripts/buildprod.sh

          - name: Install Goose
            run: go install github.com/pressly/goose/v3/cmd/goose@latest
          
          - name: Migration
            run: ./scripts/migrate.sh
